### ISSUE TITLE
Cannot compile with MSYS

### ISSUE THREAD

**Issue by ShinkoNet** [archshift/xorer#4]
When running make using cmake, I get some errors in main.cpp.

http://pastebin.com/LjMTxCQy

Programming error?

**Comment by rctgamer3** [comment]
Same here.
Editing ncch.h and adding `#include <string.h>` at the top fixed it for me.

**Comment by archshift** [comment]
Fixed, sorry.

**Comment by ShinkoNet** [comment]
I've tried your fixed version and I've also tried to use the code rctgamer3 said, yet it still doesn't build. I get the same error.

**Comment by archshift** [comment]
Are you sure you're trying the latest master? I even set up CI for both Linux and Windows, so i'm not sure what to tell you if you're still experiencing building problems.

**Comment by ShinkoNet** [comment]
I'm sure, I deleted the old one and downloaded the new master (I can tell because it has a new #include code). Is it because I built cmake with the MSYS generator?

**Comment by socram8888** [comment]
#8 should fix this
